# Etapa de compilación y pruebas
FROM maven:3.8.3-openjdk-11-slim AS build

# Copia el código fuente y el archivo pom.xml a la imagen
COPY pom.xml /app/
COPY src /app/src/

# Establece el directorio de trabajo
WORKDIR /app

# Compila y ejecuta las pruebas
RUN mvn clean test

# Etapa de compilación y ejecución del microservicio
FROM maven:3.8.3-openjdk-11-slim

# Copia los archivos compilados de la etapa anterior a la imagen
COPY --from=build /app/target/TechhubApplication.jar /app/

# Establece el directorio de trabajo
WORKDIR /app

# Ejecuta el microservicio
CMD ["java", "-jar", "TechhubApplication.jar"]